"""update decrement inventory function

Revision ID: 078e08b77466
Revises: c466efee0658
Create Date: 2026-05-26 00:06:11.994491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078e08b77466'
down_revision: Union[str, Sequence[str], None] = 'c466efee0658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("""
        CREATE OR REPLACE FUNCTION decrement_inventory()
        RETURNS TRIGGER AS $$
        BEGIN

            UPDATE inventory
            SET stock_quantity = stock_quantity - NEW.quantity
            WHERE catalogue_id = NEW.catalogue_id
            AND stock_quantity >=NEW.quantity;
            
            IF NOT FOUND THEN
               RAISE EXCEPTION
               'Insufficient stock for product ID %',
               NEW.catalogue_id;
            END IF;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
