"""add timestamps and jsonb indexes

Revision ID: 15bd2d21d1f1
Revises: bdf65cca261e
Create Date: 2026-05-20 23:58:05.431676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15bd2d21d1f1'
down_revision: Union[str, Sequence[str], None] = 'bdf65cca261e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column(
        'attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('catalogue', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('catalogue', sa.Column('updated_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_catalogue_attributes_gin', 'catalogue', [
                    'attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_catalogue_price'),
                    'catalogue', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_price'), table_name='catalogue')
    op.drop_index('ix_catalogue_attributes_gin',
                  table_name='catalogue', postgresql_using='gin')
    op.drop_column('catalogue', 'updated_at')
    op.drop_column('catalogue', 'created_at')
    op.drop_column('catalogue', 'attributes')
    # ### end Alembic commands ###
