"""create_catalogue_table

Revision ID: 68fccddc2ba6
Revises: 
Create Date: 2026-05-07 23:31:34.374198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fccddc2ba6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_id'), 'catalogue', ['id'], unique=False)
    op.create_index(op.f('ix_catalogue_sku'), 'catalogue', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_sku'), table_name='catalogue')
    op.drop_index(op.f('ix_catalogue_id'), table_name='catalogue')
    op.drop_table('catalogue')
    # ### end Alembic commands ###
