"""add tags and tag gin index

Revision ID: b7fad8923659
Revises: 15bd2d21d1f1
Create Date: 2026-05-21 10:14:46.404736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7fad8923659'
down_revision: Union[str, Sequence[str], None] = '15bd2d21d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column('tags', postgresql.ARRAY(
        sa.String()), nullable=False, server_default='{}'))
    op.alter_column('catalogue', 'tags',
                    server_default=None)
    op.create_index('ix_catalogue_tags_gin', 'catalogue', [
                    'tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalogue_tags_gin',
                  table_name='catalogue', postgresql_using='gin')
    op.alter_column('catalogue', 'attributes',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False,
                    existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('catalogue', 'tags')
    # ### end Alembic commands ###
