"""add_price_and_stock_to_catalogue

Revision ID: bdf65cca261e
Revises: 68fccddc2ba6
Create Date: 2026-05-09 14:06:49.402337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf65cca261e'
down_revision: Union[str, Sequence[str], None] = '68fccddc2ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('catalogue', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue', 'stock_quantity')
    op.drop_column('catalogue', 'price')
    # ### end Alembic commands ###
