"""split inventory from catalogue

Revision ID: c466efee0658
Revises: 5cbbed5cdb57
Create Date: 2026-05-25 23:50:50.216651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c466efee0658'
down_revision: Union[str, Sequence[str], None] = '5cbbed5cdb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogue_id')
    )
    op.create_index(op.f('ix_inventory_warehouse_location'), 'inventory', ['warehouse_location'], unique=False)
    op.add_column('catalogue', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('catalogue', sa.Column('category', sa.String(), nullable=False))
    op.create_index('ix_catalogue_category_price', 'catalogue', ['category', 'price'], unique=False)
    op.drop_column('catalogue', 'stock_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_catalogue_category_price', table_name='catalogue')
    op.drop_column('catalogue', 'category')
    op.drop_column('catalogue', 'is_active')
    op.drop_index(op.f('ix_inventory_warehouse_location'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
