"""truncate_orders_table_and drop_triggers_and_functions

Revision ID: e8788dddefba
Revises: 078e08b77466
Create Date: 2026-06-01 16:38:45.887766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8788dddefba'
down_revision: Union[str, Sequence[str], None] = '078e08b77466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.execute("DROP TRIGGER IF EXISTS trg_decrement_inventory ON orders;")
    op.execute("DROP FUNCTION IF EXISTS decrement_inventory();")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalogue_is_active'),
                    'catalogue', ['is_active'], unique=False)
    op.create_table('orders',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('catalogue_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('quantity', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('quantity > 0', name=op.f(
                        'check_quantity_positive')),
                    sa.ForeignKeyConstraint(
                        ['catalogue_id'], ['catalogue.id'], name=op.f('orders_catalogue_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
                    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###
