# configure services
services:
  catalogue-api:
    build: .
    container_name: catalogue_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - cache
    command: >
      sh -c "
      python wait_for_db.py &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: on-failure

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine

volumes:
  pgdata: