upstream catalogue_cluster {
    server catalogue-api:8000 max_fails=3 fail_timeout=30s;
}

upstream order_cluster {
    server order-api:8010 max_fails=3 fail_timeout=30s;
}

upstream auth_cluster {
    server auth-api:8020 max_fails=3 fail_timeout=30s;
}

server {

    listen 80;

    # Proxy settings apply to all locaations below
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    # Added these for timeouts

    # proxy_connect_timeout 10s;
    # proxy_read_timeout 5s;
    # proxy_send_timeout 5s;

    # To add an api endpoint for different versions just add a location for api/v1

    # Catalogue
    location /api/catalogue/ {
        rewrite ^/api/catalogue/(.*)$ /catalogue/$1 break;
        proxy_pass http://catalogue_cluster/;
    }

    # Orders
    location /api/orders/ {
        rewrite ^/api/orders/(.*)$ /orders/$1 break;
        proxy_pass http://order_cluster/;
    }

    # Auth
    location /api/auth/ {
        rewrite ^/api/auth/(.*)$ /auth/$1 break;
        proxy_pass http://auth_cluster/;
    }
}