upstream catalogue_cluster {
    server catalogue-api:8000;
}

server {
    listen 80;
    location / {
        proxy_pass http://catalogue_cluster;
        proxy_set_header Host $host;
        
    }
}